#ifndef FLAGS_H
#define FLAGS_H

#include <Arduino.h>

#define DEVICE_MODE_FULL_FEATURES   "DEVICE_MODE_FULL_FEATURES"
// #define DEVICE_MODE_NO_ACTUATORS    "DEVICE_MODE_NO_ACTUATORS"
// #define DEVICE_MODE_NO_SENSORS      "DEVICE_MODE_NO_SENSORS"

#endif // FLAGS_H